In [1]:
#!pip install opencv-python

   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   -- ------------------------------------- 2.4/38.8 MB 16.8 MB/s eta 0:00:03
   ------------- -------------------------- 12.8/38.8 MB 36.7 MB/s eta 0:00:01
   ------------------ --------------------- 18.1/38.8 MB 32.6 MB/s eta 0:00:01
   ------------------------ --------------- 23.9/38.8 MB 30.8 MB/s eta 0:00:01
   ---------------------------- ----------- 28.0/38.8 MB 28.7 MB/s eta 0:00:01
   --------------------------------- ------ 32.2/38.8 MB 26.9 MB/s eta 0:00:01
   ------------------------------------- -- 36.4/38.8 MB 25.7 MB/s eta 0:00:01
   ---------------------------------------- 38.8/38.8 MB 24.7 MB/s eta 0:00:00


In [8]:
from PIL import Image
import numpy as np
import cv2
import matplotlib.pyplot as plt
from scipy import ndimage

In [10]:
def display(title, img):
    cv2.imshow(title, img)
    # Chờ một khoảng thời gian
    cv2.waitKey(10000)
    # Đóng window
    cv2.destroyWindow(title)

In [12]:
path= 'E:/TGMT/anh/2.jpg'
img = cv2.imread(path)
# In thông tin của ảnh
print(img)

[[[ 51  16  13]
  [ 51  16  13]
  [ 51  16  13]
  ...
  [123  61  53]
  [119  54  46]
  [148  83  75]]

 [[ 51  16  13]
  [ 51  16  13]
  [ 51  16  13]
  ...
  [120  57  49]
  [122  57  49]
  [163  98  90]]

 [[ 51  16  13]
  [ 51  16  13]
  [ 51  16  13]
  ...
  [128  63  55]
  [120  55  47]
  [136  68  61]]

 ...

 [[ 73  23  25]
  [ 73  23  25]
  [ 73  23  25]
  ...
  [253 245 255]
  [253 245 255]
  [254 246 255]]

 [[ 73  23  25]
  [ 73  23  25]
  [ 73  23  25]
  ...
  [253 245 255]
  [254 246 255]
  [254 246 255]]

 [[ 73  23  25]
  [ 73  23  25]
  [ 73  23  25]
  ...
  [254 246 255]
  [254 246 255]
  [254 246 255]]]


In [13]:
# Hiển thị ảnh
cv2.imshow('Window', img)
# Chờ một khoảng thời gian
cv2.waitKey(10000)
# Đóng window
cv2.destroyWindow('Window')

In [14]:
# Tách màu
b, g, r = cv2.split(img)
cv2.imshow('Window', img)
cv2.imshow('Red', r)
cv2.imshow('Green', g)
cv2.imshow('Blue', b)

# Chờ một khoảng thời gian
cv2.waitKey(0)
# Đóng window
cv2.destroyAllWindows()

In [15]:
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.imshow('Window', img)
cv2.imshow('gray_img', gray_img)
cv2.imshow('img_2', img_2)
# Chờ một khoảng thời gian
cv2.waitKey(0)
# Đóng window
cv2.destroyAllWindows()

In [17]:
# Thay đổi thông số của điểm ảnh
height, width, z = img.shape
quater_h = height/2
quater_w = width/2

# geen color
green_color = (0,255,0)

# copy ảnh
img2 = img.copy()

# thay đổi màu của góc 1/4 bên trái trên

for y in range(int(quater_h)):
    for x in range(int(quater_w)):
        img2[y, x] = green_color
# Hiển thị
display('Window', img)
display('Window-2', img2)